input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [message] {
    mutate {
      add_field => { "source" => "hms-backend" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "hms-logs-%{+YYYY.MM.dd}"
  }
}
